server:
  port: 8090
spring:
  datasource:
    name: BOOT_DATA_SOURCE
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://z2glrumsvli01:3306/report?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=UTC
    username: report_admin
    password: west123
    platform: mysql
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    port: 6379
    password:
    database: 1
    host: 127.0.0.1
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
    timeout: 1s
  cache:
      redis:
        use-key-prefix: true
        time-to-live: 60s